version: "3.8"
services:
  service_remtochkacom:
    image: volodyanrg/debian_nginx_php
    ports: # dev-mode
      - "80:80"
    volumes:
      - ./volume:/var/www
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  default:
    name: mynet
    external: true