version: "3.8"
services:
  service_remtochkacom:
    image: volodyanrg/debian-bullseye-slim_nginx_php8
    ports: # dev-mode
      - "127.0.0.1:80:80" # 127... для локальной-dev разработки
    volumes:
      - ./volume:/var/www
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  default:
    name: mynet
    external: true